"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { AuthProvider } from "./contexts/authContext";
import { Amatic_SC } from "next/font/google";
import { HeroUIProvider } from '@heroui/react'
import { ToastProvider } from "@heroui/toast";
import Footer from "../app/components/Footer";
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query';
import {useEffect} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amatic = Amatic_SC({
  subsets: ["cyrillic"], // или ['cyrillic'], если нужен кириллический шрифт
  display: "swap",
  weight: ["400", "700"], // выбираешь нужные начертания
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const queryClient = new QueryClient();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <QueryClientProvider client={queryClient}>
            <AuthProvider>
              <Navbar />
                <HeroUIProvider>
                  <ToastProvider />
                    <div className="mt-6 flex flex-col items-center min-h-[calc(96vh-4rem)]">{children}</div>
                  <Footer />
                </HeroUIProvider>
            </AuthProvider>
        </QueryClientProvider>
        </body>
    </html>
  );
}
