"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { AuthProvider } from "./contexts/authContext";
import { Amatic_SC } from "next/font/google";
import { HeroUIProvider } from '@heroui/react'
import { ToastProvider } from "@heroui/toast";
import Footer from "../app/components/Footer";
import { PlayerProvider } from 'next-playerjs-wrapper'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amatic = Amatic_SC({
  subsets: ["cyrillic"], // или ['cyrillic'], если нужен кириллический шрифт
  display: "swap",
  weight: ["400", "700"], // выбираешь нужные начертания
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <script src="//site.com/playerjs.js" type="text/javascript"></script>
    </head>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          <PlayerProvider player='/playerjs.js'>
            <HeroUIProvider>
              <ToastProvider />
              <div className="mt-4 flex flex-col items-center min-h-[calc(96vh-4rem)]">{children}</div>
              <Footer />
            </HeroUIProvider>
          </PlayerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
